//
// Created by alina on 2018-09-14.
//

#ifndef CISC_361_PROGRAMMING_ASSIGNMENT_01B_MAIN_H
#define CISC_361_PROGRAMMING_ASSIGNMENT_01B_MAIN_H

int main(int argc, char *argv[]);

#endif //CISC_361_PROGRAMMING_ASSIGNMENT_01B_MAIN_H

